version: "3.7"

services: 
    relations:
        build: 
            args:
                user: api
                uid: 1000
            context: ./backend-
            dockerfile: Dockerfile
        image: backend
        container_name: backend
        restart: unless-stopped
        working_dir: /backend-api
        volumes: 
            - ./backend-:/backend-api 
        ports: 
            - "3333:3333"
        networks: 
            - learningRelations  
    db: 
        image: postgres
        container_name: database
        restart: always
        environment: 
            - POSTGRES_DB=database
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports: 
            - "5432:5432"
        volumes: 
            - ./postgres-data:/var/lib/postgresql/data
        networks:
            - learningRelations

networks: 
    learningRelations: 
        driver: bridge 
